version: '3.9'

services:
  nginx:
    container_name: nginx
    restart: always
    env_file: ./.env
    tty: true
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
      args:
        SERVER_URL: ${SERVER_URL}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt/live/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/privkey.pem:/etc/nginx/ssl/privkey.pem 
    environment:
      SERVER_URL: ${SERVER_URL}
      SERVER_NAME: ${SERVER_NAME}
    
    networks:
      - dockernetwork


  server:
    container_name: server
    image: server
    env_file: ./.env
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      SERVER_PORT: ${SERVER_PORT}
    networks:
      - dockernetwork
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    env_file: /.env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - dockernetwork

networks:
  dockernetwork:
    driver: bridge

